//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace WAM_Core.DataModels
{
	/// <summary>
	/// Database       : WAM_DB
	/// Data Source    : WAM_DB
	/// Server Version : 3.19.3
	/// </summary>
	public partial class WamDbDB : LinqToDB.Data.DataConnection
	{
		public ITable<InstalledAddon> InstalledAddons { get { return this.GetTable<InstalledAddon>(); } }
		public ITable<Setting>        Settings        { get { return this.GetTable<Setting>(); } }

		public WamDbDB()
		{
			InitDataContext();
		}

		public WamDbDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("InstalledAddon")]
	public partial class InstalledAddon
	{
		[PrimaryKey, NotNull] public string AddonGuid     { get; set; } // text(max)
		[Column,     NotNull] public string AddonName     { get; set; } // text(max)
		[Column,     NotNull] public string GitUrl        { get; set; } // text(max)
		[Column,     NotNull] public long   AutoUpdate    { get; set; } // integer
		[Column,     NotNull] public string LastCheckDate { get; set; } // text(max)
		[Column,     NotNull] public string InstallDate   { get; set; } // text(max)
	}

	[Table("Setting")]
	public partial class Setting
	{
		[Column("Setting_Id"), PrimaryKey,  Identity] public long   SettingId    { get; set; } // integer
		[Column(),             NotNull              ] public string SettingName  { get; set; } // text(max)
		[Column(),                Nullable          ] public string SettingValue { get; set; } // text(max)
	}

	public static partial class TableExtensions
	{
		public static InstalledAddon Find(this ITable<InstalledAddon> table, string AddonGuid)
		{
			return table.FirstOrDefault(t =>
				t.AddonGuid == AddonGuid);
		}

		public static Setting Find(this ITable<Setting> table, long SettingId)
		{
			return table.FirstOrDefault(t =>
				t.SettingId == SettingId);
		}
	}
}
