//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : ManagerDatabase
	/// Data Source    : ManagerDatabase
	/// Server Version : 3.14.2
	/// </summary>
	public partial class ManagerDatabaseDB : LinqToDB.Data.DataConnection
	{
		public ITable<InstalledAddon> InstalledAddons { get { return this.GetTable<InstalledAddon>(); } }
		public ITable<Setting>        Settings        { get { return this.GetTable<Setting>(); } }

		public ManagerDatabaseDB()
		{
			InitDataContext();
		}

		public ManagerDatabaseDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("InstalledAddon")]
	public partial class InstalledAddon
	{
		[PrimaryKey, NotNull] public string AddonGuid     { get; set; } // text(max)
		[Column,     NotNull] public string AddonName     { get; set; } // text(max)
		[Column,     NotNull] public string GitUrl        { get; set; } // text(max)
		[Column,     NotNull] public long   AutoUpdate    { get; set; } // integer
		[Column,     NotNull] public string LastCheckDate { get; set; } // text(max)
		[Column,     NotNull] public string InstallDate   { get; set; } // text(max)
	}

	[Table("Setting")]
	public partial class Setting
	{
		[Column, NotNull    ] public string SettingName  { get; set; } // text(max)
		[Column,    Nullable] public string SettingValue { get; set; } // text(max)
	}

	public static partial class TableExtensions
	{
		public static InstalledAddon Find(this ITable<InstalledAddon> table, string AddonGuid)
		{
			return table.FirstOrDefault(t =>
				t.AddonGuid == AddonGuid);
		}
	}
}
