//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : AddonDb
	/// Data Source    : AddonDb
	/// Server Version : 3.14.2
	/// </summary>
	public partial class AddonDbDB : LinqToDB.Data.DataConnection
	{
		public ITable<Addon> Addons { get { return this.GetTable<Addon>(); } }

		public AddonDbDB()
		{
			InitDataContext();
		}

		public AddonDbDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("Addon")]
	public partial class Addon
	{
		[PrimaryKey, NotNull] public string AddonGuid { get; set; } // text(max)
		[Column,     NotNull] public string AddonName { get; set; } // text(max)
		[Column,     NotNull] public string GitUrl    { get; set; } // text(max)
	}

	public static partial class TableExtensions
	{
		public static Addon Find(this ITable<Addon> table, string AddonGuid)
		{
			return table.FirstOrDefault(t =>
				t.AddonGuid == AddonGuid);
		}
	}
}
